apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellowedwhale-deployment
  labels:
    app: hellowedwhale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellowedwhale
  template:
    metadata:
      labels:
        app: hellowedwhale 
    spec:
      containers:
      - name: hellowedwhale
        image: umarmaan882/hellowhale:v2
        ports:
        - containerPort: 80
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: wedwhale-service
spec:
  selector:
    app: hellowedwhale 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31117
